=== ShekharGlobal/Corporate/WebServices and RestFul Api/Examples/Products.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT products (product+)>
<!ELEMENT product (name, description, type, quantity)>
<!ATTLIST product id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ATTLIST type comments CDATA #IMPLIED>
<!ELEMENT quantity (#PCDATA)>

=== ShekharGlobal/Corporate/WebServices and RestFul Api/Examples/Products.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE products SYSTEM "products.dtd">
<products>
    <product id="p1">
        <name>Cheetos</name>
        <description>Fritos Baked Puffs</description>
        <type comments="Snacks">Grocery</type>
        <quantity>25</quantity>
    </product>
    <product id="p2">
        <name>Levi Jeans</name>
        <description>Model LF28</description>
        <type comments="Men's wear">Apparel</type>
        <quantity>10</quantity>
    </product>
    <product id="p3">
        <name>Sony Vaio Laptop</name>
        <description>Model VGN NW270F</description>
        <type>Electronics</type>
        <quantity>5</quantity>
    </product>
</products>
